<Project Sdk="Microsoft.NET.Sdk">
  <!-- DAL (Data Access Layer): EF Core + SQLite, repositories -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="$(EfCoreVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BE\BE.csproj" />
  </ItemGroup>
</Project>
